name: CI

on:
  push:
    branches:
      - main
      - feature-continous-integration
  pull_request:
    branches:
      - main
      - feature-continous-integration
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
